version: "3.7"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - 3000:3000
    links:
      - prometheus
  prometheus-exporter:
    build: ./prometheus-exporter
    ports:
      - 9877:9877
  carbon-aware-sdk-webapi:
    image: carbon-aware-sdk-webapi  # Note this is built manually for now from the carbon aware source code
    environment:
      CarbonAwareVars__CarbonIntensityDataSource: WattTime
      WattTimeClient__Username: ${WattTimeClient__Username}
      WattTimeClient__Password: ${WattTimeClient__Password}
    ports:
      - 8080:80