name: ci

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Prometheus
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:prometheus"
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/carbon-plugin-prometheus
      - name: Build and push Grafana
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:grafana"
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/carbon-plugin-grafana
      - name: Build and push Exporter
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}"
          file: ./prometheus-exporter/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/carbon-plugin-prometheus-exporter