name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Prometheus
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:prometheus"
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/carbon-plugin-prometheus:$RELEASE_VERSION
      - name: Build and push Grafana
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:grafana"
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/carbon-plugin-grafana:$RELEASE_VERSION
      - name: Build and push Exporter
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:carbon-monitor/prometheus-exporter"
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/carbon-plugin-prometheus-exporter:$RELEASE_VERSION
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: generate-compose.yml
          # Optional, directory where playbooks live
          directory: ./
          options: |
            --extra-vars version=$RELEASE_VERSION
      - name: Test playbook
        run: |
          cat compose.yml